### PR TITLE
docs: add description of isolate packages

### LINKED ISSUE #2: Update to v4.1.5
### Added

- Add `find`, `remove`, `updateItem` and `toArray` functions to `PriorityQueue`.
- Support single package release (use scope @js-sdsl).

### Fixed

- Get wrong tree index when size is 0.

### Added

- Add `index` property to tree iterator which represents the sequential index of the iterator in the tree.

### Changed

- Minimal optimization with private properties mangling, macro inlining and const enum.
- Private properties are now mangled.
- Remove `checkWithinAccessParams` function.
- Constants of `HashContainer` are moved to `HashContainerConst` const enum.
- The iteratorType parameter in the constructor now changed from `boolean` type to `IteratorType` const enum type.
- The type of `TreeNode.color` is now changed from `boolean` to `TreeNodeColor` const enum.
- Turn some member exports into export-only types.

### Fixed

- Fixed wrong iterator error message.

### PR DESCRIPTION
**Pull request by noname0310**
For Chinese, I used a translator. I don't think it'll be too weird, but there'll be some problems.

### CODE REVIEW

**Comment by ZLY201** [comment]
Just English, I'll do translate.

**Comment by ZLY201** [comment]
Sorry, I forgot this PR.

Please refer to this PR and make it better.

https://github.com/js-sdsl/js-sdsl/pull/78/files

And I think this should be add to `start/introduction.md` but not `/more`.

**Comment by noname0310** [comment]
@ZLY201 Let me know if you have anything else to add

**Comment by ZLY201** [comment]
> @ZLY201 Let me know if you have anything else to add

That's enougth I think.

If you have some idea, just submit a new PR. :)

**Comment by noname0310** [comment]
Please translate it into Chinese

**Pull request merged**
